"""add answer user, relationship

Revision ID: 411eeee860be
Revises: dcc5c9b01319
Create Date: 2025-08-07 02:03:04.286007

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '411eeee860be'
down_revision: Union[str, None] = 'dcc5c9b01319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answers', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'user_id')
    # ### end Alembic commands ###
