"""empty message

Revision ID: 4c45c0acb28c
Revises: 
Create Date: 2025-08-08 14:43:48.648538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c45c0acb28c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('answers', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'answers', 'users', ['user_id'], ['id'])
    op.add_column('questions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'user_id')
    op.drop_constraint(None, 'answers', type_='foreignkey')
    op.drop_column('answers', 'user_id')
    # ### end Alembic commands ###
