"""add question user, relationship

Revision ID: dcc5c9b01319
Revises: 74f6b192745b
Create Date: 2025-08-07 01:58:04.947436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcc5c9b01319'
down_revision: Union[str, None] = '74f6b192745b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('questions', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'user_id')
    # ### end Alembic commands ###